name: Build iPod App

"on":
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Get project
        uses: actions/checkout@v4
      - name: Build iPod app
        run: |
          xcodebuild \
            -project iPodWheelPrototype.xcodeproj \
            -scheme iPodWheelPrototype \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Save iPhone simulator app
        uses: actions/upload-artifact@v4
        with:
          name: iPodWheelPrototype-Simulator
          path: iPodWheelPrototype.build/Debug-iphonesimulator/iPodWheelPrototype.app
