name: Build iPod App

"on":
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Get project
        uses: actions/checkout@v4
      - name: Build iPod app
        run: |
          xcodebuild \
            -project iPodWheelPrototype.xcodeproj \
            -scheme iPodWheelPrototype \
            -sdk iphones \
            -configuration Debug \
            -destination 'generic/platform=iOS \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build


      - name: Save iPhone  app
        uses: actions/upload-artifact@v4
        with:
          name: iPodWheelPrototype-iphone
          path: build/Build/Products/Debug-iphoneos/iPodWheelPrototype.app
